# Default values for codeapi.
replicaCount: 1

image:
  repository: "registry.agentsmp.com/backstage-agent"
  tag: "v0.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

ingress:
  enabled: false
