version: '3.8'
services:
  api:
    build: .
    container_name: codeapi-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
