apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codeapi.fullname" . }}
  labels:
    {{- include "codeapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "codeapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "codeapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: codeapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: OPENAI_API_KEY
              value: "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"
            - name: GIT_USERNAME
              value: "shashankdatt08"
            - name:  GIT_PAT
              value: "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"
